### ISSUE TITLE
trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by dpossas** [yajra/laravel-datatables-html#60] opened 2018-03-17 11:27 UTC
### Summary of problem or feature request

After update v3.7.1 an error ocourred:

trim() expects parameter 1 to be string, array given - /vendor/yajra/laravel-datatables-html/src/Html/Builder.php on line 162

protected function isCallbackFunction($value, $key)
    {
        return Str::startsWith(trim($value), $this->config->get('datatables-html.callback', ['$', '$.', 'function'])) || Str::contains($key, 'editor');
    }

### System details

- Operating System - Ubuntu 14.04
- PHP Version 7.1
- Laravel Version 5.5
- Laravel-DataTables Version 3.7.1

**Comment by padre** [comment] 2018-09-20 15:55
@dpossas any solution?

**Comment by yajra** [comment] 2018-09-21 01:37
@dpossas can you please provide some snippets to reproduce the issue? Thanks!

**Comment by padre** [comment] 2018-09-21 14:20
Hi @yajra First of all, thank you very much for the tool!

The latest version that works for me is https://github.com/yajra/laravel-datatables-html/blob/dfedf116ea0e6579a6eb7fc963675d0b95316284/src/Html/Builder.php

Since then, the instruction {!! $dataTable->scripts() !!} causes the following error:

trim() expects parameter 1 to be string, object given - /vendor/yajra/laravel-datatables-html/src/Html/Builder.php on line 168

```
    protected function isCallbackFunction($value, $key)
    {
        if (empty($value)) {
            return false;
        }
        return Str::startsWith(trim($value), $this->config->get('datatables-html.callback', ['$', '$.', 'function'])) || Str::contains($key, 'editor');
    }
```
$value = {#802}
$key = "language.oPaginate"


 "language" => array:14 [▼
    "sProcessing" => "Procesando..."
    "sLengthMenu" => "_MENU_"
    "sZeroRecords" => "No se encontraron resultados"
    "sEmptyTable" => "Ningún dato disponible en esta tabla"
    "sInfo" => "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros"
    "sInfoEmpty" => "Mostrando registros del 0 al 0 de un total de 0 registros"
    "sInfoFiltered" => "(filtrado de un total de _MAX_ registros)"
    "sInfoPostFix" => ""
    "sSearch" => ""
    "sUrl" => ""
    "sInfoThousands" => ","
    "sLoadingRecords" => "Cargando..."
    "oPaginate" => {#802}
    "oAria" => {#803}
  ]

**Comment by yajra** [comment] 2022-05-07 16:38
Should be fixed in latest versions.

**Closed by yajra** 2022-05-07 16:38 UTC
Labels: for review, need feedback
